name: Jô Salermo
favicon: null
layout_spectrum: 0.6262153033167124
typography_spectrum: 0.5919411182403564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7459860625676811
  lightness: 0.03222813759930432
  saturation: 0.2501630084589124
  rhythmicContrast: 0.26002525445073843
purpose: []
