name: Jô Salermo
favicon: null
layout_spectrum: 0.99416
typography_spectrum: 0.75543
title: 'Personal Organizer Rio de Janeiro, RJ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211f20'
    - '#e1e1e1'
    - '#666566'
    - '#bdbdbe'
  brandStrength: 0.7459860625676811
  lightness: 0.03222813759930432
  saturation: 0.2501630084589124
  rhythmicContrast: 0.26002525445073843
purpose: []
