name: Jô Salermo
favicon: null
layout_spectrum: 0.99416
typography_spectrum: 0.75543
title: 'JÔ SALERMO - Personal Organizer - Rio de Janeiro, RJ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ebd8'
    - '#a89989'
    - '#6d8690'
    - '#d9be9f'
    - '#615951'
  brandStrength: 0.7459860625676811
  lightness: 0.375
  saturation: 0.2501630084589124
  rhythmicContrast: 0.25
purpose: []
